version: "3.8"

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: framesash
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local
